---
title: ""
author: "Konrad Semsch"
date: "2019-11-XX"
slug: 
tags: ["tidymodels", "predictive modelling", "feature interactions"]
categories: ["predictive modelling"]
output:
  blogdown::html_page:
    highlight: tango
---

```{r, echo = FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE
)
```

<style>
body {
text-align: justify}
</style>

Excerpt

<!--more-->

Excerpt

# Introduction

# A bit of theory

# Initial setup

```{r message=FALSE, warning=FALSE, results="hide"}

### Install the development versions of these packages
# devtools::install_github("tidymodels/dials")
# devtools::install_github("tidymodels/parsnip")
# devtools::install_github("tidymodels/tune")

```

```{r message=FALSE, warning=FALSE, results="hide"}

set.seed(42)
options(max.print = 150)

library(lubridate)
library(tidyverse)
library(doFuture)
library(magrittr)
library(tidymodels)
library(parsnip)
library(dials)
library(tune)

# let's parallelize the compuations  
all_cores <- parallel::detectCores(logical = FALSE)

registerDoFuture()
cl <- makeCluster(all_cores)
plan(cluster, workers = cl)

```

```{r}

download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00383/risk_factors_cervical_cancer.csv", destfile = "data_cancer.csv", method = "auto")

data_cancer_raw <- read_csv("data_cancer.csv")
file.remove("data_cancer.csv") # you can remove the file from your local directory if you like

data_cancer_raw %<>%
  set_names(., tolower(names(.)))

glimpse(data_cancer_raw)

```

# Data cleansing

```{r}

# References: 
# https://github.com/christophM/interpretable-ml-book/blob/master/R/get-cervical-cancer-dataset.R
# http://archive.ics.uci.edu/ml/datasets/Cervical+cancer+%28Risk+Factors%29

data_cancer <- data_cancer_raw %>% 
  na_if("?") %>% 
  mutate(
    biopsy = factor(biopsy, levels = c(0, 1), labels = c("healthy", "cancer")) 
  ) %>% 
  rename(
    target = biopsy,
    n_sex_partners = `number of sexual partners`,
    first_sex_intercourse = `first sexual intercourse`,
    n_pregnancies = `num of pregnancies`,
    smokes_years = `smokes (years)`,
    hormonal_cceptives = `hormonal contraceptives`,
    hormonal_cceptives_years = `hormonal contraceptives (years)`,
    iud_years = `iud (years)`,
    std_number = `stds (number)`,
    std_number_diagnosis = `stds: number of diagnosis`,
    std_time_since_first_diagnosis = `stds: time since first diagnosis`,
    std_time_since_last_diagnosis = `stds: time since last diagnosis`,
    dx_cancer = `dx:cancer`,
    dx_cin = `dx:cin`,
    dx_hpv = `dx:hpv`
  ) %>% 
  transmute(
    target = target,
    age = age,
    
    n_sex_partners = as.numeric(n_sex_partners),
    first_sex_intercourse = as.numeric(first_sex_intercourse),
    n_pregnancies = as.numeric(n_pregnancies),
    
    smokes = as.factor(smokes),
    smokes_years = as.numeric(smokes_years),
    
    hormonal_cceptives = as.factor(hormonal_cceptives),
    hormonal_cceptives_years = as.numeric(hormonal_cceptives_years),
    
    iud = as.factor(iud),
    iud_years = as.numeric(iud_years),
    
    stds = as.factor(stds),
    std_number = as.numeric(std_number),
    std_number_diagnosis = as.numeric(std_number_diagnosis),
    std_time_since_first_diagnosis = as.numeric(std_time_since_first_diagnosis),
    std_time_since_last_diagnosis = as.numeric(std_time_since_last_diagnosis),
    
    dx_cancer = as.factor(dx_cancer),
    dx_cin = as.factor(dx_cin),
    dx_hpv = as.factor(dx_hpv),
    dx = as.factor(dx)
  )

glimpse(data_cancer)

```

```{r}

round(prop.table(table(data_cancer$target)), 2)

```

```{r}

naniar::miss_var_summary(data_cancer)

```


# Preparing the recipe

```{r}

recipe_en <- data_cancer %>%
  recipe(target ~ .) %>%
  step_
  
  # Imputation: assigning NAs to a new level for categorical 
  # (that's good practice, but not needed here) and median imputation for numeric
  step_unknown(all_nominal(), -status) %>% 
  step_medianimpute(all_numeric()) %>%

  # Combining infrequent categorical levels and introducing a new level 
  # for prediction time (that's good practice, but not needed here)
  step_other(all_nominal(), -status, other = "infrequent_combined") %>%
  step_novel(all_nominal(), -status, new_level = "unrecorded_observation") %>%

  # Hot-encoding categorical variables
  step_dummy(all_nominal(), -status, one_hot = TRUE) %>%
  
  # Creating additional ratio variables - they typically make sense 
  # in credit scoring problems
  step_mutate(
    ratio_expenses_income = expenses / (income + 0.001),
    ratio_assets_income = assets / (income + 0.001),
    ratio_debt_income = debt / (income + 0.001),
    ratio_debt_assets = debt / (assets + 0.001),
    ratio_amout_price = amount / (price + 0.001)
  ) %>% 
  
  # Adding upsampling 
  step_upsample(status, over_ratio = tune())

```

```{r}

(engine <- rand_forest(
  mtry = 2,
  trees = 500, 
  min_n = 10
  ) %>% 
  set_mode("classification") %>% 
  set_engine("ranger"))

```

```{r}

(grid <- grid_regular(
  over_ratio() %>% range_set(c(0.5, 1.5)),
  levels = 11
  ))

```

```{r max.print = 10}

(fits <- tune_grid(
  recipe,
  model = engine,
  rs = train_cv,
  grid = grid,
  perf = metric_set(roc_auc, j_index, sens, spec),
  control = grid_control(verbose = FALSE)
  ))

```

```{r}

estimate(fits) %>% 
  arrange(desc(over_ratio))

```

# Analyzing performance profile

```{r message=FALSE, warning=FALSE}

library(ggrapid)

estimate(fits) %>% 
  mutate(
    over_ratio = as.character(over_ratio)
    ) %>% 
  rename(
    Metric = .metric  
  ) %>% 
  plot_line(
    over_ratio, 
    mean, 
    fill = Metric,
    title = "Performance metrics across different upsampling ratio values",
    caption = "Upsampling ratio = 1 - equal classes frequency",
    lab_x = "Upsampling ratio between both classes",
    lab_y = "Performance metric value",
    angle = 0,
    limit_max = 1
    )

```

```{r}

(over_ratio_best <- estimate(fits) %>% 
  filter(.metric == "j_index") %>% 
  arrange(desc(mean)) %>% 
  slice(1) %>% 
  pull(over_ratio))

```

```{r}

recipe_best <- recipe
recipe_best$steps[[7]] <- update(recipe$steps[[7]], over_ratio = over_ratio_best)

```

```{r}

recipe_best_prep <- prep(recipe_best, retain = TRUE)

(fit_best <- engine %>% 
  fit(status ~ ., juice(recipe_best_prep)))

```

